# Generated by Django 5.2.15 on 2026-07-03 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('stage', models.PositiveSmallIntegerField(choices=[(1, 'Stage 1 — Accumulation'), (2, 'Stage 2 — Advancing'), (3, 'Stage 3 — Distribution'), (4, 'Stage 4 — Declining')])),
                ('current_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('ma_30w', models.DecimalField(decimal_places=4, max_digits=14)),
                ('price_vs_ma_pct', models.FloatField(help_text='Percent distance of price above/below 30-week MA')),
                ('ma_slope_pct', models.FloatField(help_text='Percent change in 30-week MA over lookback period')),
                ('suggested_action', models.CharField(max_length=50)),
                ('breakout_level', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('support_level', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('stage_reasons', models.JSONField(default=list, help_text='Transparent list of factors used in stage detection')),
                ('chart_payload', models.JSONField(default=dict, help_text='Serialized weekly OHLCV + MA for Chart.js')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'ticker')},
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'watchlist items',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'ticker')},
            },
        ),
    ]
