# Generated by Django 5.2.15 on 2026-07-01 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('symbols', models.TextField(help_text='Comma-separated symbols')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('capital', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_trades', models.PositiveIntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('profit_factor', models.FloatField(default=0.0)),
                ('max_drawdown_pct', models.FloatField(default=0.0)),
                ('avg_rr', models.FloatField(default=0.0)),
                ('total_return_pct', models.FloatField(default=0.0)),
                ('equity_curve', models.JSONField(default=list)),
                ('trades', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('sector', models.CharField(blank=True, default='', max_length=100)),
                ('is_nifty200', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sales_growth_yoy', models.FloatField(blank=True, null=True)),
                ('profit_growth', models.FloatField(blank=True, null=True)),
                ('roe_5yr_avg', models.FloatField(blank=True, null=True)),
                ('debt_equity', models.FloatField(blank=True, null=True)),
                ('peg', models.FloatField(blank=True, null=True)),
                ('institutional_interest', models.CharField(blank=True, default='', help_text='stable / increasing / decreasing (placeholder)', max_length=20)),
                ('last_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('avg_volume_20d', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='StrategyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('enable_fundamental_filters', models.BooleanField(default=False)),
                ('sales_growth_min', models.FloatField(default=8.0, help_text='YoY sales growth % min')),
                ('profit_growth_min', models.FloatField(default=10.0, help_text='Profit growth % min')),
                ('roe_min', models.FloatField(default=12.0, help_text='5-yr avg ROE % min')),
                ('debt_equity_max', models.FloatField(default=1.0)),
                ('peg_max', models.FloatField(default=2.0)),
                ('adx_min', models.FloatField(default=20.0)),
                ('adx_preferred', models.FloatField(default=25.0)),
                ('rsi_low', models.FloatField(default=40.0)),
                ('rsi_high', models.FloatField(default=65.0)),
                ('volume_multiplier', models.FloatField(default=1.5, help_text='Entry vol vs 20d avg')),
                ('ema_pullback_tolerance_pct', models.FloatField(default=2.0)),
                ('fib_low', models.FloatField(default=0.382)),
                ('fib_high', models.FloatField(default=0.618)),
                ('risk_pct', models.FloatField(default=0.75, help_text='Max risk per trade % of capital')),
                ('min_risk_reward', models.FloatField(default=2.0)),
                ('atr_sl_buffer', models.FloatField(default=0.5, help_text='ATR multiplier below SL')),
                ('capital_default', models.DecimalField(decimal_places=2, default=500000, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Strategy Configuration',
                'verbose_name_plural': 'Strategy Configurations',
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('confluence_score', models.PositiveSmallIntegerField(default=0)),
                ('is_valid', models.BooleanField(default=False)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('target_1r', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('target_2r', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('target_3r', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('risk_reward', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('position_size', models.PositiveIntegerField(default=0)),
                ('capital_used', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('reasons', models.JSONField(default=list)),
                ('rejection_reasons', models.JSONField(default=list)),
                ('indicator_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='trading.stock')),
            ],
            options={
                'ordering': ['-date', '-confluence_score'],
                'unique_together': {('stock', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TradeJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('target', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.signal')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='trading.stock')),
            ],
            options={
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to='trading.stock')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('open', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.BigIntegerField(default=0)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='trading.stock')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['stock', 'date'], name='trading_dai_stock_i_852caf_idx')],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
