# Generated by Django 5.2.15 on 2026-07-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_nifty100',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='strategyconfig',
            name='capital_default',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=14),
        ),
        migrations.AlterField(
            model_name='strategyconfig',
            name='risk_pct',
            field=models.FloatField(default=2.0, help_text='Max risk per trade % of capital'),
        ),
    ]
