# Generated by Django 5.2.15 on 2026-07-13 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_add_nifty100_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Paper Account', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('auto_trade', models.BooleanField(default=False, help_text='When on, engine auto-places orders on active F&O signals')),
                ('starting_capital', models.DecimalField(decimal_places=2, default=500000, max_digits=14)),
                ('cash', models.DecimalField(decimal_places=2, default=500000, help_text='Free cash (not blocked as margin)', max_digits=14)),
                ('margin_blocked', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('risk_pct', models.FloatField(default=1.5, help_text='Risk per trade % of equity')),
                ('max_trades_per_day', models.PositiveSmallIntegerField(default=4)),
                ('instruments', models.JSONField(default=list, help_text='e.g. ["NIFTY", "BANKNIFTY"]')),
                ('realized_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('peak_equity', models.DecimalField(decimal_places=2, default=500000, max_digits=14)),
                ('last_tick_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('trade', 'Trade'), ('warn', 'Warn'), ('error', 'Error')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='trading.paperaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(db_index=True, max_length=20)),
                ('side', models.CharField(choices=[('SHORT', 'Short'), ('LONG', 'Long')], default='SHORT', max_length=5)),
                ('lots', models.PositiveIntegerField()),
                ('lot_size', models.PositiveIntegerField()),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entry_time', models.DateTimeField()),
                ('signal_bar_time', models.CharField(blank=True, default='', max_length=32)),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target', models.DecimalField(decimal_places=2, max_digits=12)),
                ('margin_blocked', models.DecimalField(decimal_places=2, max_digits=14)),
                ('risk_pts', models.FloatField(default=0)),
                ('ml_prob', models.FloatField(blank=True, null=True)),
                ('strategy_name', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=10)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='trading.paperaccount')),
            ],
            options={
                'ordering': ['-entry_time'],
            },
        ),
        migrations.CreateModel(
            name='PaperTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(db_index=True, max_length=20)),
                ('side', models.CharField(max_length=5)),
                ('lots', models.PositiveIntegerField()),
                ('lot_size', models.PositiveIntegerField()),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField()),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exit_reason', models.CharField(choices=[('stop_loss', 'Stop Loss'), ('target', 'Target'), ('force_exit', 'Force Exit (EOD)'), ('manual', 'Manual')], max_length=20)),
                ('pnl', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pnl_pts', models.FloatField(default=0)),
                ('r_multiple', models.FloatField(default=0)),
                ('risk_pts', models.FloatField(default=0)),
                ('ml_prob', models.FloatField(blank=True, null=True)),
                ('strategy_name', models.CharField(blank=True, default='', max_length=100)),
                ('session_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.paperaccount')),
                ('position', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_trade', to='trading.paperposition')),
            ],
            options={
                'ordering': ['-exit_time'],
            },
        ),
        migrations.AddIndex(
            model_name='paperposition',
            index=models.Index(fields=['account', 'status', 'instrument'], name='trading_pap_account_e95dec_idx'),
        ),
    ]
