# Generated by Django 5.2.15 on 2026-08-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_paper_trading'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_nifty_smallcap250',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
