# Generated by Django 5.2.15 on 2026-07-03 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('sector', models.CharField(blank=True, default='', max_length=100)),
                ('weekly_stage', models.PositiveSmallIntegerField(choices=[(1, 'Stage 1 — Accumulation'), (2, 'Stage 2 — Advancing'), (3, 'Stage 3 — Distribution'), (4, 'Stage 4 — Declining')])),
                ('daily_stage', models.PositiveSmallIntegerField(choices=[(1, 'Stage 1 — Accumulation'), (2, 'Stage 2 — Advancing'), (3, 'Stage 3 — Distribution'), (4, 'Stage 4 — Declining')])),
                ('quality_score', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('rs_rating', models.FloatField(default=0.0, help_text='Relative strength score 0-100')),
                ('rs_trend', models.CharField(default='flat', max_length=20)),
                ('benchmark', models.CharField(default='NIFTY50', max_length=20)),
                ('breakout_type', models.CharField(choices=[('none', 'No Breakout'), ('weak', 'Weak Breakout'), ('clean', 'Clean Breakout')], default='none', max_length=10)),
                ('market_favorable', models.BooleanField(default=False)),
                ('current_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('ma_30w', models.DecimalField(decimal_places=4, max_digits=14)),
                ('ma_150d', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('primary_entry', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('pullback_entry', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('risk_reward', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('suggested_action', models.CharField(blank=True, default='', max_length=100)),
                ('score_breakdown', models.JSONField(default=dict)),
                ('analysis_details', models.JSONField(default=dict)),
                ('chart_payload', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_v2_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-quality_score', '-updated_at'],
                'unique_together': {('user', 'ticker')},
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('sector', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_v2_watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'watchlist items',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'ticker')},
            },
        ),
    ]
