# Generated by Django 5.2.15 on 2026-07-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage_analysis_v2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanCache',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('payload', models.JSONField(default=list)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('filters', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
